/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int PAR = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int WHILE = 4;
  /** RegularExpression Id. */
  int DO = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int MULT = 9;
  /** RegularExpression Id. */
  int EQ = 10;
  /** RegularExpression Id. */
  int NEQ = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int LE = 13;
  /** RegularExpression Id. */
  int GT = 14;
  /** RegularExpression Id. */
  int GE = 15;
  /** RegularExpression Id. */
  int LPAREN = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int LBRACKET = 18;
  /** RegularExpression Id. */
  int RBRACKET = 19;
  /** RegularExpression Id. */
  int LBRACE = 20;
  /** RegularExpression Id. */
  int RBRACE = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int COLON = 24;
  /** RegularExpression Id. */
  int PERIOD = 25;
  /** RegularExpression Id. */
  int ASSIGN = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int VAR = 28;
  /** RegularExpression Id. */
  int IF = 29;
  /** RegularExpression Id. */
  int THEN = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int NOP = 32;
  /** RegularExpression Id. */
  int VARIABLE = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "\"par\"",
    "<NUMBER>",
    "\"while\"",
    "\"do\"",
    "\"end\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\":=\"",
    "\"&&\"",
    "\"var\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"nop\"",
    "<VARIABLE>",
  };

}
